import java.sql.*;
import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class AddReceiver extends javax.swing.JFrame {

    private static AddReceiver obj=null;
    
    
    /**
     * Creates new form AddReceiver
     */
    private AddReceiver() {
        initComponents();
        citizenshipComboBox.setSelectedItem("Nepal");
        provienceComboBox.setVisible(true);
        districtComboBox.setVisible(true);
        lbl_country.setVisible(false);
        countryTextField.setVisible(false);
        stateTextField.setVisible(false);
        streetTextfield.setVisible(false);
    }

    
    public static AddReceiver getObj()
    {
        if (obj==null)
        {
            obj=new AddReceiver();
        }
        return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        motherTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fatherTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        provienceComboBox = new javax.swing.JComboBox<>();
        countryTextField = new javax.swing.JTextField();
        districtComboBox = new javax.swing.JComboBox<>();
        citizenshipComboBox = new javax.swing.JComboBox<>();
        lbl_country = new javax.swing.JLabel();
        citizenshipNoTextfield = new javax.swing.JTextField();
        streetTextfield = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        GENDERBOX = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        DOBS = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel1.setText("ADD NEW RECEIVER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 364, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 1090, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 423, 1090, 10));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 76, 30, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("New Receiver ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 74, -1, -1));

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 200, -1));

        contactTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Father's Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mother's Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, -1));

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        motherTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(motherTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contact Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, -1));

        fatherTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fatherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fatherTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Citizenship");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Citizenship Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 140, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("State / Provience");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("District / Street");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 140, -1));

        provienceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province No 1", "Madhesh Pradesh", "Bagmati Pradesh", "Gandaki Pradesh", "Lumbini Pradesh", "Karnali Pradesh", "Sudur Pashchim Pradesh" }));
        provienceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provienceComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(provienceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 160, -1));
        getContentPane().add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 118, 160, -1));

        districtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(districtComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 160, -1));

        citizenshipComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nepal", "Others", " " }));
        citizenshipComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(citizenshipComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 160, -1));

        lbl_country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_country.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_country.setText("Country");
        getContentPane().add(lbl_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 90, -1));
        getContentPane().add(citizenshipNoTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 160, -1));
        getContentPane().add(streetTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 160, -1));

        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 160, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Gender");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        GENDERBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GENDERBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        GENDERBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERBOXActionPerformed(evt);
            }
        });
        getContentPane().add(GENDERBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Date of Birth");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));
        getContentPane().add(DOBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 180, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
setVisible(false);
new AddReceiver().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String r_id = jLabel11.getText();
        String name = nameTextField.getText();
        String father = fatherTextField.getText();
        String mother = motherTextField.getText();
        String contact = contactTextField.getText();
        String email = emailTextField.getText();
        String citizen = (String)citizenshipComboBox.getSelectedItem();
        String c_no = citizenshipNoTextfield.getText();
        String provience = (String)provienceComboBox.getSelectedItem();
        String district = (String)districtComboBox.getSelectedItem();
        String country = null ;
        String gender = (String)GENDERBOX.getSelectedItem();
        
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String DOB =dFormat.format(DOBS.getDate());
        
         if(citizenshipComboBox.getSelectedItem().equals("Nepal"))
        {
            country = "Nepal";
        }
        else if(citizenshipComboBox.getSelectedItem().equals("Others"))
        {
             country = (String)countryTextField.getText();
        }
        
        
        
        try{
            Connection con =ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into receiver(receiverId,name,father_name,mother_name,contactNo,email,citizenship,citizenship_number,provience,district,country,gender,DOB) values('"+r_id+"','"+name+"','"+father+"','"+mother+"','"+contact+"','"+email+"','"+citizen+"','"+c_no+"','"+provience+"','"+district+"','"+country+"','"+gender+"','"+DOB+"')");
            JOptionPane.showMessageDialog(null,"data registered successfully");
            setVisible(false);
            AddReceiver.getObj().setVisible(true);
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
          try{
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        ResultSet rs= st.executeQuery("select max(receiverId) from receiver");
        if(rs.first())
        {
            int id =rs.getInt(1);
            id=id+1;
            String str=String.valueOf(id);
            jLabel11.setText(str);
        }
        else
        {
            jLabel11.setText("1");
        }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_formComponentShown

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void motherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherTextFieldActionPerformed

    private void fatherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherTextFieldActionPerformed

    private void provienceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provienceComboBoxActionPerformed
        // TODO add your handling code here:
         if(provienceComboBox.getSelectedItem().equals("Province No 1"))
        {
            districtComboBox.removeAllItems();
            districtComboBox.addItem("Bhojpur");
            districtComboBox.addItem("Dhankuta");
            districtComboBox.addItem("Ilam");
            districtComboBox.addItem("Jhapa");
            districtComboBox.addItem("Khotang");
            districtComboBox.addItem("Khotang");
            districtComboBox.addItem("Okhaldhunga");
            districtComboBox.addItem("Panchthar");
            districtComboBox.addItem("Sankhuwasabha");
            districtComboBox.addItem("Solukhumbu");
            districtComboBox.addItem("Sunsari");
            districtComboBox.addItem("Taplejung");
            districtComboBox.addItem("Terhathum");
            districtComboBox.addItem("Udayapur");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Madhesh Pradesh"))
        {
            districtComboBox.removeAllItems();
            districtComboBox.addItem("Bara");
            districtComboBox.addItem("Dhanusa");
            districtComboBox.addItem("Mahottari");
            districtComboBox.addItem("Parsa");
            districtComboBox.addItem("Rauthat");
            districtComboBox.addItem("Saptari");
            districtComboBox.addItem("Sarlahi");
            districtComboBox.addItem("Siraha");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Bagmati Pradesh"))
        {
            districtComboBox.removeAllItems();
            //ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bhaktapur ");
            districtComboBox.addItem("Chitwan");
            districtComboBox.addItem("Dhading");
            districtComboBox.addItem("Dolakha");
            districtComboBox.addItem("Kathmandu");
            districtComboBox.addItem("Kavrepalanchok");
            districtComboBox.addItem("Lalitpur");
            districtComboBox.addItem("Makawanpur");
            districtComboBox.addItem("Nuwakot");
            districtComboBox.addItem("Ramechap");
            districtComboBox.addItem("Rasuwa");
            districtComboBox.addItem("Sindhuli");
            districtComboBox.addItem("Sindhupalanchowk");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Gandaki Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Baglung ");
            districtComboBox.addItem("Gorkha");
            districtComboBox.addItem("Kaski");
            districtComboBox.addItem("Lamjung");
            districtComboBox.addItem("Manang");
            districtComboBox.addItem("Mustang");
            districtComboBox.addItem("Myagdi");
            districtComboBox.addItem("Nawalparasi(Bardaghat Susta Purva)");
            districtComboBox.addItem("Parbat");
            districtComboBox.addItem("Syangja");
            districtComboBox.addItem("Tanahu");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Lumbini Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Arghakhanchi ");
            districtComboBox.addItem("Banke");
            districtComboBox.addItem("Bardiya");
            districtComboBox.addItem("Dang");
            districtComboBox.addItem("Gulmi");
            districtComboBox.addItem("Kapilvastu");
            districtComboBox.addItem("Nawalparasi(Bardaghat Susta Paschim)");
            districtComboBox.addItem("Palpa");
            districtComboBox.addItem("Pyuthan");
            districtComboBox.addItem("Rolpa");
            districtComboBox.addItem("Purbi Rukum");
            districtComboBox.addItem("Rupandehi");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Karnali Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Dailekh");
            districtComboBox.addItem("Dolpa");
            districtComboBox.addItem("Humla");
            districtComboBox.addItem("Jajarkot");
            districtComboBox.addItem("Jumla");
            districtComboBox.addItem("Kalikot");
            districtComboBox.addItem("Mugu");
            districtComboBox.addItem("Rukum Pashim");
            districtComboBox.addItem("Salyan");
            districtComboBox.addItem("Surkhet");
            districtComboBox.setSelectedItem(null);
        }
        else
        {
            districtComboBox.removeAllItems();
            // ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Achham");
            districtComboBox.addItem("Baitadi");
            districtComboBox.addItem("Bajhang");
            districtComboBox.addItem("Bajura");
            districtComboBox.addItem("Darchula");
            districtComboBox.addItem("Doti");
            districtComboBox.addItem("Kailali");
            districtComboBox.addItem("Kanchanpur");
            districtComboBox.setSelectedItem(null);
        }

    }//GEN-LAST:event_provienceComboBoxActionPerformed

    private void districtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtComboBoxActionPerformed

    private void citizenshipComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipComboBoxActionPerformed
        // TODO add your handling code here:
        if(citizenshipComboBox.getSelectedItem().equals("Nepal"))
        {
            provienceComboBox.setVisible(true);
            districtComboBox.setVisible(true);
            lbl_country.setVisible(false);
            countryTextField.setVisible(false);
            stateTextField.setVisible(false);
            streetTextfield.setVisible(false);
        }
        else if(citizenshipComboBox.getSelectedItem().equals("Others"))
        {
            provienceComboBox.setVisible(false);
            districtComboBox.setVisible(false);
            lbl_country.setVisible(true);
            countryTextField.setVisible(true);
            stateTextField.setVisible(true);
            streetTextfield.setVisible(true);
        }
        
    }//GEN-LAST:event_citizenshipComboBoxActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void GENDERBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENDERBOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReceiver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOBS;
    private javax.swing.JComboBox<String> GENDERBOX;
    private javax.swing.JComboBox<String> citizenshipComboBox;
    private javax.swing.JTextField citizenshipNoTextfield;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fatherTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JTextField motherTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> provienceComboBox;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetTextfield;
    // End of variables declaration//GEN-END:variables
}
