import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class DonorRegestration extends javax.swing.JFrame {

    /**
     * Creates new form DonorRegestration
     */
    private static DonorRegestration obj=null;
    
    DonorRegestration() {
        initComponents();
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
// Gets the width and height
double width = screenSize.getWidth();
double height = screenSize.getHeight();
// Subtract height of taskbar from height in my case 50 
setSize((int)width, (int)height -50);
setLocation(0,57);  // Set frame at center of the screen
setUndecorated(true); // Removes title bar
setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

setVisible(true);

 Date();
    }
    
     private void Date() {
        SimpleDateFormat ft = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String str = ft.format(new java.util.Date());
        lblDate.setText(str);
       // return str;
       
     }

    public static DonorRegestration getObj()
    {
        if(obj==null)
        {
            obj=new DonorRegestration();
        }
        return obj;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FATHERNAME = new javax.swing.JTextField();
        MOTHERNAME = new javax.swing.JTextField();
        MOBILENO = new javax.swing.JTextField();
        GENDERBOX = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        BLOODGROUPBOX = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        FULLNAME = new javax.swing.JTextField();
        districtComboBox = new javax.swing.JComboBox<>();
        provienceComboBox = new javax.swing.JComboBox<>();
        DOBS = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        citizenshipNoTextField = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1920, 860));
        setLocation(new java.awt.Point(340, 140));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel1.setText("Add New Donor");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("New Donor ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Father Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mother Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Date of Birth");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mobile No.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Gender");

        FATHERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FATHERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FATHERNAMEActionPerformed(evt);
            }
        });

        MOTHERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MOTHERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOTHERNAMEActionPerformed(evt);
            }
        });

        MOBILENO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MOBILENO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILENOActionPerformed(evt);
            }
        });

        GENDERBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GENDERBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        GENDERBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERBOXActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Blood Group");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Province");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("District");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Email");

        EMAIL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        BLOODGROUPBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BLOODGROUPBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        BLOODGROUPBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLOODGROUPBOXActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Full Name");

        FULLNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FULLNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FULLNAMEActionPerformed(evt);
            }
        });

        districtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboBoxActionPerformed(evt);
            }
        });

        provienceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province No 1", "Madhesh Pradesh", "Bagmati Pradesh", "Gandaki Pradesh", "Lumbini Pradesh", "Karnali Pradesh", "Sudur Pashchim Pradesh" }));
        provienceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provienceComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setText("Citizenship number");

        lblDate.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(FATHERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BLOODGROUPBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MOTHERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(DOBS, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MOBILENO, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(provienceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(57, 57, 57)
                                .addComponent(citizenshipNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(GENDERBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(560, 560, 560))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(FULLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FATHERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(BLOODGROUPBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MOTHERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(DOBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MOBILENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GENDERBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(provienceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel14))
                                    .addComponent(citizenshipNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(92, 92, 92)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addComponent(lblDate)))
        );

        setSize(new java.awt.Dimension(1920, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       

        try{
          Connection con =ConnectionProvider.getCon();
          Statement st=con.createStatement();// kahila kahi statement bhitra (ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY) halna vanxa...
          ResultSet rs = st.executeQuery("Select max(donorId) from donor");
          if(rs.next())// our table is not then 
          {
              int Id = rs.getInt(1);
              Id=Id+1;
              String str=String.valueOf(Id);
              jLabel2.setText(str);
              
          }
          else
              jLabel2.setText("1");
    }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void FATHERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FATHERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FATHERNAMEActionPerformed

    private void MOTHERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOTHERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOTHERNAMEActionPerformed

    private void MOBILENOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILENOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILENOActionPerformed

    private void GENDERBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENDERBOXActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible (false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setVisible(false);
new DonorRegestration().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(FULLNAME.getText().equals("")||DOBS.getDate()==null||MOBILENO.getText().equals("")||GENDERBOX.getSelectedItem().equals("")||EMAIL.getText().equals("")||BLOODGROUPBOX.getSelectedItem().equals("")||provienceComboBox.getSelectedItem().equals("")||FATHERNAME.getText().equals("")||MOTHERNAME.getText().equals("")||citizenshipNoTextField.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "INPUT ALL DETAIl");
        }
        else{

        String donor_id=jLabel2.getText();
        int donorId =Integer.parseInt(donor_id);
        String name= FULLNAME.getText();
        String fatherName= FATHERNAME.getText();
        String motherName= MOTHERNAME.getText();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String DOB =dFormat.format(DOBS.getDate());
       
       
        String gender=(String)GENDERBOX.getSelectedItem();
        String bloodGroup=(String)BLOODGROUPBOX.getSelectedItem();
        String MobileNo=MOBILENO.getText();
        String email = EMAIL.getText();
        String provience = (String)provienceComboBox.getSelectedItem();
        String district =(String)districtComboBox.getSelectedItem();
        String citizenshipNo= citizenshipNoTextField.getText();
        JOptionPane.showMessageDialog(null, "input taken");
        JOptionPane.showMessageDialog(null,lblDate.getText() );
       String date = lblDate.getText();
       
        int sid = 0;
        if("A+".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =1;
        }
        else if("A-".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =2;
        }
        else if("B+".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =3;
        }
        else if("B-".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =4;
        }
        else if("O+".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =5;
        }
        else if("O-".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =6;
        }
        else if("AB+".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =7;
        }
        else if("AB-".equals((String)BLOODGROUPBOX.getSelectedItem()))
        {
            sid =8;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"enter blood group");
            setVisible(false);
        }
       
        try{
          
          Connection con =ConnectionProvider.getCon();
         Statement st=con.createStatement();
        
       //  st.executeUpdate("insert into donor(donorId,name,fatherName,motherName,DOB,gender,blood_group,Mobile_number,email,provience,district,citizenship,citizenship_number,stockId) values('"+donorId+"','"+name+"','"+fatherName+"','"+motherName+"','"+DOB+"','"+gender+"','"+bloodGroup+"','"+MobileNo+"','"+email+"','"+provience+"','"+district+"','"+citizenship+"','"+citizenshipNo+"','"+sid+"'");
         // st.executeUpdate("update stock set unit=unit+'"+unit+"'where bloodGroup='"+bloodGroup+"'");
         st.executeUpdate("insert into donor (donorId,name,fatherName,motherName,DOB,gender,blood_group,Mobile_number,email,provience,district,citizenship_number,date_of_reg,stockId) values('"+donorId+"','"+name+"','"+fatherName+"','"+motherName+"','"+DOB+"','"+gender+"','"+bloodGroup+"','"+MobileNo+"','"+email+"','"+provience+"','"+district+"','"+citizenshipNo+"','"+date+"','"+sid+"')");
         JOptionPane.showMessageDialog(null, "updated successfully");
          setVisible(false);
          new DonorRegestration().setVisible(true);
          
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
          //JOptionPane.showMessageDialog(null,e);   
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FULLNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FULLNAMEActionPerformed

    private void BLOODGROUPBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLOODGROUPBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BLOODGROUPBOXActionPerformed

    private void provienceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provienceComboBoxActionPerformed
        // TODO add your handling code here:
        if(provienceComboBox.getSelectedItem().equals("Province No 1"))
        {
            districtComboBox.removeAllItems();
            districtComboBox.addItem("Bhojpur");
            districtComboBox.addItem("Dhankuta");
            districtComboBox.addItem("Ilam");
            districtComboBox.addItem("Jhapa");
            districtComboBox.addItem("Khotang");
            districtComboBox.addItem("Khotang");
            districtComboBox.addItem("Okhaldhunga");
            districtComboBox.addItem("Panchthar");
            districtComboBox.addItem("Sankhuwasabha");
            districtComboBox.addItem("Solukhumbu");
            districtComboBox.addItem("Sunsari");
            districtComboBox.addItem("Taplejung");
            districtComboBox.addItem("Terhathum");
            districtComboBox.addItem("Udayapur");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Madhesh Pradesh"))
        {
            districtComboBox.removeAllItems();
            districtComboBox.addItem("Bara");
            districtComboBox.addItem("Dhanusa");
            districtComboBox.addItem("Mahottari");
            districtComboBox.addItem("Parsa");
            districtComboBox.addItem("Rauthat");
            districtComboBox.addItem("Saptari");
            districtComboBox.addItem("Sarlahi");
            districtComboBox.addItem("Siraha");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Bagmati Pradesh"))
        {
            districtComboBox.removeAllItems();
            //ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bhaktapur ");
            districtComboBox.addItem("Chitwan");
            districtComboBox.addItem("Dhading");
            districtComboBox.addItem("Dolakha");
            districtComboBox.addItem("Kathmandu");
            districtComboBox.addItem("Kavrepalanchok");
            districtComboBox.addItem("Lalitpur");
            districtComboBox.addItem("Makawanpur");
            districtComboBox.addItem("Nuwakot");
            districtComboBox.addItem("Ramechap");
            districtComboBox.addItem("Rasuwa");
            districtComboBox.addItem("Sindhuli");
            districtComboBox.addItem("Sindhupalanchowk");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Gandaki Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Baglung ");
            districtComboBox.addItem("Gorkha");
            districtComboBox.addItem("Kaski");
            districtComboBox.addItem("Lamjung");
            districtComboBox.addItem("Manang");
            districtComboBox.addItem("Mustang");
            districtComboBox.addItem("Myagdi");
            districtComboBox.addItem("Nawalparasi(Bardaghat Susta Purva)");
            districtComboBox.addItem("Parbat");
            districtComboBox.addItem("Syangja");
            districtComboBox.addItem("Tanahu");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Lumbini Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Arghakhanchi ");
            districtComboBox.addItem("Banke");
            districtComboBox.addItem("Bardiya");
            districtComboBox.addItem("Dang");
            districtComboBox.addItem("Gulmi");
            districtComboBox.addItem("Kapilvastu");
            districtComboBox.addItem("Nawalparasi(Bardaghat Susta Paschim)");
            districtComboBox.addItem("Palpa");
            districtComboBox.addItem("Pyuthan");
            districtComboBox.addItem("Rolpa");
            districtComboBox.addItem("Purbi Rukum");
            districtComboBox.addItem("Rupandehi");
            districtComboBox.setSelectedItem(null);
        }

        else
        if(provienceComboBox.getSelectedItem().equals("Karnali Pradesh"))
        {
            districtComboBox.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Dailekh");
            districtComboBox.addItem("Dolpa");
            districtComboBox.addItem("Humla");
            districtComboBox.addItem("Jajarkot");
            districtComboBox.addItem("Jumla");
            districtComboBox.addItem("Kalikot");
            districtComboBox.addItem("Mugu");
            districtComboBox.addItem("Rukum Pashim");
            districtComboBox.addItem("Salyan");
            districtComboBox.addItem("Surkhet");
            districtComboBox.setSelectedItem(null);
        }
        else
        {
            districtComboBox.removeAllItems();
            // ProvienceComboBox.setSelectedItem(null);
            districtComboBox.addItem("Achham");
            districtComboBox.addItem("Baitadi");
            districtComboBox.addItem("Bajhang");
            districtComboBox.addItem("Bajura");
            districtComboBox.addItem("Darchula");
            districtComboBox.addItem("Doti");
            districtComboBox.addItem("Kailali");
            districtComboBox.addItem("Kanchanpur");
            districtComboBox.setSelectedItem(null);
        }

    }//GEN-LAST:event_provienceComboBoxActionPerformed

    private void districtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorRegestration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorRegestration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BLOODGROUPBOX;
    private com.toedter.calendar.JDateChooser DOBS;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField FATHERNAME;
    private javax.swing.JTextField FULLNAME;
    private javax.swing.JComboBox<String> GENDERBOX;
    private javax.swing.JTextField MOBILENO;
    private javax.swing.JTextField MOTHERNAME;
    private javax.swing.JTextField citizenshipNoTextField;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JComboBox<String> provienceComboBox;
    // End of variables declaration//GEN-END:variables

    private void executeUpdate(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
