import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
 
import java.util.Date;  
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class UpdateDetailDonor extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDetailDonor
     */
    
    private static UpdateDetailDonor obj=null;
    
    private  UpdateDetailDonor() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
// Gets the width and height
double width = screenSize.getWidth();
double height = screenSize.getHeight();
// Subtract height of taskbar from height in my case 50 
setSize((int)width, (int)height -50);
setLocation(0,57);  // Set frame at center of the screen
setUndecorated(true); // Removes title bar
setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

setVisible(true);
    }

    public static UpdateDetailDonor getObj()
    {
        if(obj==null)
        {
            obj=new UpdateDetailDonor();
        }
        return obj;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FULLNAME = new javax.swing.JTextField();
        FATHERNAME = new javax.swing.JTextField();
        MOTHERNAME = new javax.swing.JTextField();
        MOBILENO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BLOODGROUP = new javax.swing.JComboBox<>();
        provience = new javax.swing.JComboBox<>();
        district = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        CITIZENSHIP_NO = new javax.swing.JTextField();
        DOBS = new com.toedter.calendar.JCalendar();
        GENDERBOX = new javax.swing.JComboBox<>();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel1.setText("Update User Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 339, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1920, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("User ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 71, 26));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 164, 26));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 1920, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 178, 112, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 138, 112, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mother Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 228, 112, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Date of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 268, 112, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mobile No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 112, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 112, -1));

        FULLNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FULLNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FULLNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(FULLNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 138, 163, -1));

        FATHERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FATHERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FATHERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(FATHERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 188, 163, -1));

        MOTHERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MOTHERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOTHERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(MOTHERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 228, 163, -1));

        MOBILENO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MOBILENO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILENOActionPerformed(evt);
            }
        });
        getContentPane().add(MOBILENO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 163, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 141, 62, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Blood Group");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 178, 90, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Province");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 221, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("District");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 259, 75, -1));

        EMAIL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });
        getContentPane().add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 138, 220, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 494, 80, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 494, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 494, -1, -1));

        BLOODGROUP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        getContentPane().add(BLOODGROUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 178, 220, -1));

        provience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province No 1", "Madhesh Pradesh", "Bagmati Pradesh", "Gandaki Pradesh", "Lumbini Pradesh", "Karnali Pradesh", "Sudur Pashchim Pradesh" }));
        provience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provienceActionPerformed(evt);
            }
        });
        getContentPane().add(provience, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 218, 220, -1));

        district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtActionPerformed(evt);
            }
        });
        getContentPane().add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 258, 222, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Citizenship Number");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 311, -1, -1));

        CITIZENSHIP_NO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CITIZENSHIP_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CITIZENSHIP_NOActionPerformed(evt);
            }
        });
        getContentPane().add(CITIZENSHIP_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1154, 308, 220, -1));
        getContentPane().add(DOBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 160, 20));

        GENDERBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GENDERBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        GENDERBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERBOXActionPerformed(evt);
            }
        });
        getContentPane().add(GENDERBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 170, -1));

        setSize(new java.awt.Dimension(1920, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MOTHERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOTHERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOTHERNAMEActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateDetailDonor().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String donorId=jTextField1.getText();//yes la donorid namak aayta variable ma value get garxa
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select name, fathername, mothername, DOB,Mobile_number, gender, email, blood_group, provience, district, citizenship_number from donor where donorId='"+donorId+"'");
            if(rs.next())//if donorid exist then next next garda 
            {
 /*yo field ma set gara k resultset ko value or string*/           //yes la aayako value show garxa
            FULLNAME.setText(rs.getString(1));
            FATHERNAME.setText(rs.getString(2));
            MOTHERNAME.setText(rs.getString(3));
            String date = rs.getString(4);
           Date date1=new SimpleDateFormat("dd-MM-yyyy").parse(date);  
          DOBS.setDate(date1);
            MOBILENO.setText(rs.getString(5));
            GENDERBOX.setSelectedItem(rs.getString(6));
            EMAIL.setText(rs.getString(7));
           // BLOODGROUP.setText(rs.getString(9));
           // BLOODGROUP.setString(rs.getSelectedItem(9));
           
           
           
           
           String bloodGroup=rs.getString("blood_group");
           BLOODGROUP.setSelectedItem(bloodGroup);
           
           String Provience = rs.getString("provience");
            provience.setSelectedItem(Provience);
            
            String District =rs.getString("district");
            district.setSelectedItem(District);
            
            
           CITIZENSHIP_NO.setText(rs.getString(11));
              
            }
            else{
                JOptionPane.showMessageDialog(null,"Donor Does Not Exist");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String donorId=jTextField1.getText();
        String name= FULLNAME.getText();
        String fatherName= FATHERNAME.getText();
        String motherName= MOTHERNAME.getText();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String DOB =dFormat.format(DOBS.getDate());
        String MobileNo=MOBILENO.getText();
        String gender=(String)GENDERBOX.getSelectedItem();
        String email = EMAIL.getText();
        //String bloodGroup=BLOODGROUP.getText();
        String bloodGroup=(String) BLOODGROUP.getSelectedItem();
        String Provience =(String) provience.getSelectedItem();
        String District=(String)district.getSelectedItem();
        String c_no = CITIZENSHIP_NO.getText();
        
        try{
          Connection con =ConnectionProvider.getCon();
         Statement st=con.createStatement();
         st.executeUpdate("Update donor set name='"+name+"',fatherName='"+fatherName+"',motherName='"+motherName+"',DOB='"+DOB+"',Mobile_number='"+MobileNo+"',gender='"+gender+"',email='"+email+"',blood_group='"+bloodGroup+"',provience='"+Provience+"',district='"+District+"',citizenship_number='"+c_no+"' where donorId='"+donorId+"' ");
        
         JOptionPane.showMessageDialog(null,"Successfully Updated");
          setVisible(false);
          new UpdateDetailDonor().setVisible(true);
          
        }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(null,e);   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FULLNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FULLNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FULLNAMEActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void provienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provienceActionPerformed
        // TODO add your handling code here:
        if(provience.getSelectedItem().equals("Province No 1"))
        {
            district.removeAllItems();
            district.addItem("Bhojpur");
            district.addItem("Dhankuta");
            district.addItem("Ilam");
            district.addItem("Jhapa");
            district.addItem("Khotang");
            district.addItem("Khotang");
            district.addItem("Okhaldhunga");
            district.addItem("Panchthar");
            district.addItem("Sankhuwasabha");
            district.addItem("Solukhumbu");
            district.addItem("Sunsari");
            district.addItem("Taplejung");
            district.addItem("Terhathum");
            district.addItem("Udayapur");
            district.setSelectedItem(null);
        }

        else
        if(provience.getSelectedItem().equals("Madhesh Pradesh"))
        {
            district.removeAllItems();
            district.addItem("Bara");
            district.addItem("Dhanusa");
            district.addItem("Mahottari");
            district.addItem("Parsa");
            district.addItem("Rauthat");
            district.addItem("Saptari");
            district.addItem("Sarlahi");
            district.addItem("Siraha");
            district.setSelectedItem(null);
        }

        else
        if(provience.getSelectedItem().equals("Bagmati Pradesh"))
        {
            district.removeAllItems();
            //ProvienceComboBox.setSelectedItem(null);
            district.addItem("Bhaktapur ");
            district.addItem("Chitwan");
            district.addItem("Dhading");
            district.addItem("Dolakha");
            district.addItem("Kathmandu");
            district.addItem("Kavrepalanchok");
            district.addItem("Lalitpur");
            district.addItem("Makawanpur");
            district.addItem("Nuwakot");
            district.addItem("Ramechap");
            district.addItem("Rasuwa");
            district.addItem("Sindhuli");
            district.addItem("Sindhupalanchowk");
            district.setSelectedItem(null);
        }

        else
        if(provience.getSelectedItem().equals("Gandaki Pradesh"))
        {
            district.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            district.addItem("Baglung ");
            district.addItem("Gorkha");
            district.addItem("Kaski");
            district.addItem("Lamjung");
            district.addItem("Manang");
            district.addItem("Mustang");
            district.addItem("Myagdi");
            district.addItem("Nawalparasi(Bardaghat Susta Purva)");
            district.addItem("Parbat");
            district.addItem("Syangja");
            district.addItem("Tanahu");
            district.setSelectedItem(null);
        }

        else
        if(provience.getSelectedItem().equals("Lumbini Pradesh"))
        {
            district.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            district.addItem("Arghakhanchi ");
            district.addItem("Banke");
            district.addItem("Bardiya");
            district.addItem("Dang");
            district.addItem("Gulmi");
            district.addItem("Kapilvastu");
            district.addItem("Nawalparasi(Bardaghat Susta Paschim)");
            district.addItem("Palpa");
            district.addItem("Pyuthan");
            district.addItem("Rolpa");
            district.addItem("Purbi Rukum");
            district.addItem("Rupandehi");
            district.setSelectedItem(null);
        }

        else
        if(provience.getSelectedItem().equals("Karnali Pradesh"))
        {
            district.removeAllItems();
            //  ProvienceComboBox.setSelectedItem(null);
            district.addItem("Dailekh");
            district.addItem("Dolpa");
            district.addItem("Humla");
            district.addItem("Jajarkot");
            district.addItem("Jumla");
            district.addItem("Kalikot");
            district.addItem("Mugu");
            district.addItem("Rukum Pashim");
            district.addItem("Salyan");
            district.addItem("Surkhet");
            district.setSelectedItem(null);
        }
        else
        {
            district.removeAllItems();
            // ProvienceComboBox.setSelectedItem(null);
            district.addItem("Achham");
            district.addItem("Baitadi");
            district.addItem("Bajhang");
            district.addItem("Bajura");
            district.addItem("Darchula");
            district.addItem("Doti");
            district.addItem("Kailali");
            district.addItem("Kanchanpur");
            district.setSelectedItem(null);
        }
    }//GEN-LAST:event_provienceActionPerformed

    private void CITIZENSHIP_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CITIZENSHIP_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CITIZENSHIP_NOActionPerformed

    private void FATHERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FATHERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FATHERNAMEActionPerformed

    private void MOBILENOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILENOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILENOActionPerformed

    private void districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtActionPerformed

    private void GENDERBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENDERBOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDetailDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDetailDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDetailDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDetailDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDetailDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BLOODGROUP;
    private javax.swing.JTextField CITIZENSHIP_NO;
    private com.toedter.calendar.JCalendar DOBS;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField FATHERNAME;
    private javax.swing.JTextField FULLNAME;
    private javax.swing.JComboBox<String> GENDERBOX;
    private javax.swing.JTextField MOBILENO;
    private javax.swing.JTextField MOTHERNAME;
    private javax.swing.JComboBox<String> district;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> provience;
    // End of variables declaration//GEN-END:variables
}
